classic/urls.py
from django.urls import path

from . import views


app_name = 'classic'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('contest/', views.ContestRedirect.as_view(), name='contest_redirect'),
    path('contest/answer/', views.AnswerPost.as_view(), name='answer_post'),
    path('contest/answer/edit/', views.AnswerEdit.as_view(), name='answer_edit'),
    path('contest/mark/', views.AnswerMarkTop.as_view(), name='answer_mark_top'),
    path('contest/mark/post/<slug:level_name>/', views.AnswerMarkPost.as_view(), name='answer_mark_post'),
    path('contest/mark/confirm/<slug:level_name>/', views.AnswerMarkConfirm.as_view(), name='answer_mark_confirm'),
    path('contest/mark/done/<slug:level_name>/', views.AnswerMarkDone.as_view(), name='answer_mark_done'),
    path('contest/results/', views.ContestList.as_view(), name='contest_list'),
    path('contest/results/<int:contest_id>/', views.ContestDetail.as_view(), name='contest_detail'),
    path('contest/results/<int:contest_id>/<slug:level_name>/', views.MatchDetail.as_view(), name='match_detail'),
    path('gallery/', views.GalleryTop.as_view(), name='gallery_top'),
    path('gallery/<int:answer_id>/', views.GalleryDetail.as_view(), name='gallery_detail'),
    path('question/post/', views.QuestionPost.as_view(), name='question_post'),
    path('question/check/', views.QuestionCheck.as_view(), name='question_check'),

    #path('api/ajax-post-search/', views.ajax_post_search, name='ajax_post_search'),
    path('api/post-favorite/', views.api.post_favorite, name='api_post_favorite'),
    path('api/post-comment/', views.api.post_comment, name='api_post_comment'),
    #path('api/ajax-sort-answer/', views.ajax_sort_answer, name='ajax_sort_answer'),
    path('api/check-question/', views.api.check_question, name='api_check_question'),
]

common/urls.py
from django.urls import path

from . import views


app_name = 'common'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('signup/done/', views.UserCreateDone.as_view(), name='signup_done'),
    path('signup/complete/<str:token>/', views.UserCreateComplete.as_view(), name='signup_complete'),
    path('settings/', views.UserSettingsList.as_view(), name='user_settings_list'),
    path('settings/update/', views.user_settings_update, name='user_settings_update'),
    path('password/change/', views.PasswordChange.as_view(), name='password_change'),
    path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<username>/', views.UserDetail.as_view(), name='user_detail'),

    path('api/icon-upload/', views.api.icon_upload, name='api_icon_upload'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('classic/', include('classic.urls')),
    path('scramble/', include('scramble.urls')),
    path('', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classic/models/answer_review.py
from django.db import models
from django.contrib.auth import get_user_model
from django.apps import apps

Answer = apps.get_model('classic', 'Answer', require_ready=False)
User = get_user_model()


class AnswerReview(models.Model):
    answer = models.ForeignKey(
        Answer,
        on_delete=models.CASCADE,
        verbose_name='投票回答',
        related_name="answer_reviews",
        related_query_name="answer_review",
    )
    reviewer = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name='投票者',
        related_name="answer_reviews",
        related_query_name="answer_review",
    )
    POINT_CHOICES = [
        (0, '0点'),
        (2, '2点'),
        (3, '3点'),
        (4, '4点')
    ]
    point = models.IntegerField(
        verbose_name='点数',
        choices=POINT_CHOICES,
        blank=True,
        default=0
    )


    class Meta:
        verbose_name = '採点詳細'
        verbose_name_plural = '採点詳細'
        ordering = ['-id', ]
        constraints = [
            models.UniqueConstraint(
                fields=['answer', 'reviewer'],
                name='unique_answer_review'
            )
        ]

classic/models/level.py
from tokenize import Triple
from django.db import models
from django.apps import apps

Contest = apps.get_model('classic', 'Contest', require_ready=False)


class Level(models.Model):
    name = models.SlugField(
        "レベル",
        unique=True
    )
    color = models.CharField(
        "カラー",
        max_length=100,
        blank=True
    )
    order = models.IntegerField(
        'オーダー',
        unique=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'レベル'
        verbose_name_plural = 'レベル'
        ordering = ['order', ]

classic/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.admin.widgets import AdminTextareaWidget, AdminTextInputWidget
from django.shortcuts import get_object_or_404

from .models import Question, Answer, AnswerReview, AnswerComment, Favorite, QuestionCheck, Contest, Level, Match

# 管理サイト用のQuestionForm
class QuestionAdminForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__' # 結局のところ，Metaで定義したfields属性は無視されるらしい
        widgets = {
            'text': AdminTextareaWidget(),
        }


# 管理サイト用のAnswerForm
class AnswerAdminForm(ModelForm):
    class Meta:
        model = Answer
        fields = '__all__'
        widgets = {
            'text': AdminTextInputWidget(),
        }


class AnswerCommentAdminForm(ModelForm):
    class Meta:
        model = AnswerComment
        fields = '__all__'

# 管理サイト用のFavoriteForm
class FavoriteAdminForm(ModelForm):
    class Meta:
        model = Favorite
        fields = '__all__'


# 管理サイト用のFavoriteForm
class QuestionCheckAdminForm(ModelForm):
    class Meta:
        model = QuestionCheck
        fields = '__all__'


# 管理サイト用ContestForm
class ContestAdminForm(ModelForm):
    class Meta:
        model = Contest
        fields = '__all__'


# 管理サイト用のLevelForm
class LevelAdminForm(ModelForm):
    class Meta:
        model = Level
        fields = '__all__'


# 管理サイト用のMatchForm
class MatchAdminForm(ModelForm):
    class Meta:
        model = Match
        fields = '__all__'


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['text',]
        widgets = {
            'text': forms.Textarea(attrs={'rows': '3'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.label_suffix = ""


class AnswerReviewForm(forms.Form):
    pass


# 管理サイト用のAnswerReviewForm
class AnswerReviewAdminForm(ModelForm):
    class Meta:
        model = AnswerReview
        fields = '__all__'


def create_DynamicAnswerReviewForm(match_id):
    match = get_object_or_404(Match, pk=match_id)
    form_item = {}

    # create answer_review form objects
    for answer in match.answers.all().order_by('?'):
        form_item.update(
            {
                f'point_{answer.id}': forms.TypedChoiceField(
                        label=answer.text, label_suffix='', choices=AnswerReview.POINT_CHOICES, initial=0, coerce=int, empty_value=None,
                        widget=forms.RadioSelect(attrs={'class': 'btn-check', 'autocomplete': 'off'}),
                    ),
                # f'comment_{answer.id}': forms.CharField(
                #         label='', label_suffix='', max_length=20, required=False,
                #         widget=forms.TextInput(attrs={'class': 'form-control','placeholder': '20文字以内'}),
                #     ),
            }
        )

    # ReviewFormを継承した，fieldオブジェクトにform_itemを代入したDynamicReviewFormを作成
    DynamicReviewForm = type('DynamicReviewForm', (AnswerReviewForm, ), form_item)

    return DynamicReviewForm


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'image', ]
        widgets = {
            'text': forms.Textarea(attrs={'rows': '3'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.label_suffix = ""

classic/views/answer.py
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, RedirectView, UpdateView
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import Http404

from classic.models import Question, Answer, Contest, Match
from classic.forms import AnswerForm


User = get_user_model()

class AnswerPost(LoginRequiredMixin, CreateView):
    '''
    クラスベースビューで書こうとしたらこうなる
    '''
    model = Answer
    form_class = AnswerForm
    template_name = 'classic/answer_post.html'
    success_url = reverse_lazy('classic:answer_edit')


    def setup(self, request, *args, **kwargs):
        """Initialize attributes shared by all view methods."""
        super().setup(request, *args, **kwargs)
        self.kwargs['match'] = get_object_or_404(
            Match,
            contest__is_held=True,
            contest__is_asked=True,
            contest__date_asked__lte=timezone.now(),
            contest__post_deadline__gte=timezone.now(),
            level=request.user.profile.classic_level,
        )

    def dispatch(self, request, *args, **kwargs):
        # Try to dispatch to the right method; if a method doesn't exist,
        # defer to the error handler. Also defer to the error handler if the
        # request method isn't on the approved list.
        # 一度答えている場合は編集画面にリダイレクトする
        if User.objects.filter(
            pk=request.user.id,
            answer__match=self.kwargs['match']
        ).exists():
            return redirect('classic:answer_edit')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.panellist = self.request.user
        form.instance.match = self.kwargs['match']
        messages.success(self.request, "回答を投稿しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        # バリデーションに失敗した時
        messages.warning(self.request, "回答を投稿できませんでした")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        """Insert match into the context dict."""
        if 'match' not in kwargs:
            kwargs['match'] = self.kwargs['match']
        return super().get_context_data(**kwargs)


class AnswerEdit(LoginRequiredMixin, UpdateView):
    '''
    クラスベースビューで書こうとしたらこうなる
    '''
    model = Answer
    form_class = AnswerForm
    template_name = 'classic/answer_edit.html'
    success_url = reverse_lazy('classic:index')

    def form_valid(self, form):
        messages.success(self.request, "回答を投稿しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        # バリデーションに失敗した時
        messages.warning(self.request, "回答を投稿できませんでした")
        return super().form_invalid(form)

    def get_object(self, queryset=None):
        answer = get_object_or_404(
            Answer,
            match__contest__is_held=True,
            match__contest__is_asked=True,
            match__contest__date_asked__lte=timezone.now(),
            match__contest__post_deadline__gte=timezone.now(),
            match__level=self.request.user.profile.classic_level,
            panellist=self.request.user,
        )
        return answer

classic/views/contest.py
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, RedirectView, UpdateView
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import Http404

from classic.models import Question, Answer, Contest, Match
from classic.forms import AnswerForm


User = get_user_model()


class ContestList(ListView):
    model = Contest
    template_name = 'classic/contest_list.html'
    queryset = Contest.objects.filter(was_marked=True)


class ContestDetail(DetailView):
    model = Contest
    template_name = 'classic/contest_detail.html'
    pk_url_kwarg = 'contest_id'
    queryset = Contest.objects.filter(was_marked=True)


class ContestRedirect(LoginRequiredMixin, RedirectView):
    '''
        現在のコンテストが出題中か採点中なのか判別してリダイレクトする
    '''
    def get_redirect_url(self, *args, **kwargs):
        url = None
        # 現在，出題中の場合
        if Contest.objects.filter(
            is_held=True,
            is_asked=True,
            date_asked__lte=timezone.now(),
            post_deadline__gte=timezone.now(),
        ).exists():
            url = reverse('classic:answer_post')
        # 現在，採点中の場合
        elif Contest.objects.filter(
            is_held=True,
            is_marked=True,
            post_deadline__lte=timezone.now(),
            date_marked__gte=timezone.now(),
        ).exists():
            url = reverse('classic:answer_mark_top')

        return url

classic/views/gallery.py
from classic.models import Question, Answer
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404


# Create your views here.
class GalleryTop(ListView):
    template_name = 'classic/gallery_top.html'
    queryset = Answer.objects.filter(
        match__contest__was_marked=True,
    )


class GalleryDetail(DetailView):
    # model = Answer
    template_name = 'classic/gallery_detail.html'
    pk_url_kwarg = 'answer_id'
    queryset = Answer.objects.filter(
        match__contest__was_marked=True,
    )

classic/views/index.py
from django.views import generic


# Create your views here.
class Index(generic.TemplateView):
    template_name = 'classic/index.html'

classic/views/match.py
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from classic.models import Question, Answer, Contest, Match
from classic.forms import AnswerForm


class MatchDetail(DetailView):
    template_name = 'classic/match_detail.html'

    def get_object(self, queryset=None):
        match = get_object_or_404(
            Match,
            contest__was_marked=True,
            contest__id=self.kwargs.get('contest_id'),
            level__name=self.kwargs.get('level_name'),
        )
        return match

classic/views/question.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.urls import reverse_lazy

from classic.models import Question
from classic.forms import QuestionForm


class QuestionPost(LoginRequiredMixin, CreateView):
    '''
    Question投稿フォーム
    '''
    model = Question
    form_class = QuestionForm
    template_name = 'classic/question_post_form.html'
    success_url = reverse_lazy('classic:index')

    def form_valid(self, form):
        form.instance.questioner = self.request.user
        messages.success(self.request, "お題を投稿しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        # バリデーションに失敗した時
        messages.warning(self.request, "お題を投稿できませんでした")
        return super().form_invalid(form)

classic/views/question_check.py
from django.views import generic
from django.db.models import F, Q

from classic.models import Question, Answer, Contest, Match, Level, AnswerReview


# Create your views here.
class QuestionCheck(generic.TemplateView):
    template_name = 'classic/question_check.html'

    def get_context_data(self, **kwargs):
        """Insert match into the context dict."""
        context = super().get_context_data(**kwargs)
        context['question'] = Question.objects.filter(
            was_checked=False
        ).exclude(
            Q(questioner=self.request.user) |
            Q(question_check__checker=self.request.user)
        ).order_by(
            'id'
        ).first()
        return context

templates/classic/includes/answer_card.html
{% load static %}


<div class="card answer-{{ answer.id }} shadow">
    <a href="{% url 'classic:match_detail' answer.match.contest.id answer.match.level.name %}" class="card-header bg-transparent">
        <div>
            第{{ answer.match.contest.id }}回
            {{ answer.match.level }}レベル
        </div>
        {{ answer.match.question.text }}
        <div>
            {% if answer.match.question.image %}
                <img src="{{ answer.match.question.image.url }}" class="card-img-top" alt="お題画像">
            {% endif %}
        </div>
    </a>
    <div class="card-body">
        <div class="card-text">
            <div class="d-inline-block rounded-patch bg-primary me-3">
                <span class="rounded-patch-content text-white">{{ answer.rank }}</span>
            </div>
            {{ answer.text }}
        </div>
        <div class="d-flex  align-items-center">
            <a href="#answerScoreModal-{{answer.id}}" class="text-decoration-none" data-bs-toggle="modal">
                <span class="">{{ answer.score }}</span>点
            </a>
            <form class="favorite-form ms-auto" action="{% url 'classic:api_post_favorite' %}" method="POST">
                {% csrf_token %}
                {% include 'classic/includes/favorite.html' %}
            </form>
        </div>
    </div>
    <div class="card-footer bg-transparent">
        {% for answer_review in answer.answer_reviews.all %}
            {% if answer_review.comment %}
                <div class="d-flex align-items-center">
                    <a href="{% url 'common:user_detail' answer_review.reviewer.username %}" class="text-decoration-none d-block flex-shrink-0">
                        <img src="{{ answer_review.reviewer.profile.icon.url }}" class="img-profile me-1" alt="アイコン">
                        <small class="text-muted">{{ answer_review.reviewer.account_name }}</small>
                    </a>
                    <div class="ps-3 small">
                        {{ answer_review.comment }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

<!-- AnswerScoreModal -->
{% include 'classic/includes/answer_score_modal.html' %}

<!-- FavoriteUserModal -->
{% include 'classic/includes/favorite_user_modal.html' %}

templates/classic/includes/answer_card_detail.html
<div class="card answer-{{ answer.id }} shadow">
    <a href="{% url 'classic:match_detail' answer.match.contest.id answer.match.level.name %}" class="card-header bg-transparent">
        <div>
            第{{ answer.match.contest.id }}回
            {{ answer.match.level }}レベル
        </div>
        <div>
            {{ answer.match.question.text }}
        </div>
        <div>
            {% if answer.match.question.image %}
                <img src="{{ answer.match.question.image.url }}" class="card-img-top" alt="お題画像">
            {% endif %}
        </div>
        <div data-url="{% url 'common:user_detail' answer.match.question.questioner.username %}">
            <img src="{{ answer.match.question.questioner.profile.icon.url }}" class="img-profile me-1" alt="アイコン">
            <small class="text-muted">{{ answer.match.question.questioner.account_name }}</small>
        </div>
    </a>
    <div class="card-body">
        <div class="card-text">
            <div class="d-inline-block rounded-patch bg-primary me-3">
                <span class="rounded-patch-content text-white">{{ answer.rank }}</span>
            </div>
            {{ answer.text }}
        </div>
        <div class="d-flex  align-items-center">
            <a href="#answerScoreModal-{{answer.id}}" class="text-decoration-none" data-bs-toggle="modal">
                <span class="">{{ answer.score }}</span>点
            </a>
            <form class="favorite-form ms-auto" action="{% url 'classic:api_post_favorite' %}" method="POST">
                {% csrf_token %}
                {% include 'classic/includes/favorite.html' %}
            </form>
        </div>
    </div>
    <div class="card-footer bg-transparent">
        <form class="answer-comment-form" action="{% url 'classic:api_post_comment' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="answer-comment-{{answer.id}}" maxlength="20" placeholder="20文字以内" class="form-control" required>
            <button type="submit" class="btn btn-primary">コメント</button>
        </form>
        <div class="answer-comment-container">
            {% include 'classic/includes/answer_comment.html' %}
        </div>
    </div>
</div>

<!-- AnswerScoreModal -->
{% include 'classic/includes/answer_score_modal.html' %}

<!-- FavoriteUserModal -->
{% include 'classic/includes/favorite_user_modal.html' %}

templates/classic/includes/answer_comment.html
{% for answer_comment in answer.answer_comments.all %}
    <div class="d-flex align-items-center">
        <a href="{% url 'common:user_detail' answer_comment.commentator.username %}" class="text-decoration-none d-block flex-shrink-0">
            <img src="{{ answer_comment.commentator.profile.icon.url }}" class="img-profile me-1" alt="アイコン">
            <small class="text-muted">{{ answer_comment.commentator.account_name }}</small>
        </a>
        <div class="ps-3 small">
            {{ answer_comment.text }}
        </div>
    </div>
{% endfor %}

templates/classic/includes/answer_score_modal.html
<div class="modal fade" id="answerScoreModal-{{answer.id}}" tabindex="-1" aria-labelledby="answerScoreModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title" id="answerScoreModalLabel">採点詳細</p>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-2">
                <div class="p-2">
                    {{ answer.score }}点
                    {% regroup answer.answer_reviews.all|dictsortreversed:"point" by get_point_display as point_list %}

                    {% for point in point_list %}
                        {% if point.grouper != '0点' %}
                            <div class="badge rounded-pill bg-primary">
                                {{ point.grouper }}
                                <span class="badge rounded-pill bg-secondary">{{ point.list|length }}</span>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="list-group list-group-flush">
                    {% for point in point_list %}
                        {% if point.grouper != '0点' %}
                            <div class="">
                                <div class="list-group-item border-0 p-2">
                                    {{ point.grouper }}
                                    （{{ point.list|length }}）
                                </div>
                                <div class="">
                                    {% for answer_review in point.list %}
                                        <a href="{% url 'common:user_detail' answer_review.reviewer.username %}" class="list-group-item list-group-item-action border-0 rounded-3 p-2 d-flex align-items-center">
                                            <div class="me-2">
                                                <img src="{{ answer_review.reviewer.profile.icon.url }}" class="img-profile" alt="アイコン">
                                            </div>
                                            <div class="me-auto">
                                                {{ answer_review.reviewer.account_name }}
                                            </div>
                                            <div class="badge rounded-pill bg-warning me-1">
                                                {{ answer_review.reviewer.profile.classic_level }}レベル
                                            </div>
                                            <div class="badge rounded-pill bg-black">
                                                <i class="bi bi-trophy-fill"></i>
                                                {{ answer_review.reviewer.answers.count }}
                                            </div>
                                        </a>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/classic/includes/favorite.html
{% if user in answer.get_favorite_users %}
    <button class="btn" name="favorite-{{answer.id}}" type="submit"><i class="bi bi-heart-fill text-danger"></i></button>
{% else %}
    <button class="btn" name="favorite-{{answer.id}}" type="submit"><i class="bi bi-heart"></i></button>
{% endif %}

{% if answer.favorites.exists %}
    <a href="#favoriteUserModal-{{answer.id}}" class="" data-bs-toggle="modal">
        <span name="favorite-count-{{answer.id}}">{{ answer.favorites.count }}</span>件のいいね
    </a>
{% endif %}

templates/classic/includes/favorite_user_modal.html
<div class="modal fade" id="favoriteUserModal-{{answer.id}}" tabindex="-1" aria-labelledby="favoriteUserModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title" id="favoriteUserModalLabel">いいねしたユーザー</p>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-2">
                <div class="list-group list-group-flush">
                    {% for favorite in answer.favorites.all %}
                        <a href="{% url 'common:user_detail' favorite.user.username %}" class="list-group-item list-group-item-action border-0 rounded rounded-3 p-2 d-flex align-items-center">
                            <div class="me-2">
                                <img src="{{ favorite.user.profile.icon.url }}" class="img-profile" alt="アイコン">
                            </div>
                            <div class="me-auto">
                                {{ favorite.user.account_name }}
                            </div>
                            <div class="badge rounded-pill bg-warning me-1">
                                {{ favorite.user.profile.classic_level }}レベル
                            </div>
                            <div class="badge rounded-pill bg-black">
                                <i class="bi bi-trophy-fill"></i>
                                {{favorite.user.answers.count }}
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/classic/includes/question_check_modal.html
<div class="modal fade" id="checkQuestionModal" tabindex="-1" aria-labelledby="checkQuestionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title text-muted" id="checkQuestionModalLabel">お題の評価にご協力ください</p>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="check-question-text">
                    {{ question.text }}
                </div>
                <div id="check-question-image">
                    {% if question.image %}
                        <img src="{{ question.image.url }}" class="img-fluid" alt="お題画像">
                    {% endif %}
                </div>
            </div>
            <div class="modal-footer">
                <div class="container-fluid">
                    <form id="form-check-question" action="{% url 'classic:api_check_question' %}" method="POST">
                        {% csrf_token %}
                        <div class="d-flex justify-content-evenly">
                            <button type="submit" class="btn btn-primary" name="question-check-{{question.id}}" value="0" >
                                <span class="pe-1">
                                    <i class="bi bi-hand-thumbs-up-fill"></i>
                                </span>
                                いいね！
                            </button>
                            <button type="submit" class="btn btn-secondary" name="question-check-{{question.id}}" value="1">
                                <span class="pe-1">
                                    <i class="bi bi-hand-thumbs-down-fill"></i>
                                </span>
                                う〜ん...
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>