classic/urls.py
from django.urls import path

from . import views


app_name = 'classic'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('contest/', views.ContestRedirect.as_view(), name='contest_redirect'),
    path('contest/answer/', views.AnswerPost.as_view(), name='answer_post'),
    path('contest/answer/edit/', views.AnswerEdit.as_view(), name='answer_edit'),
    path('contest/mark/', views.AnswerMarkTop.as_view(), name='answer_mark_top'),
    path('contest/mark/post/<slug:level_name>/', views.AnswerMarkPost.as_view(), name='answer_mark_post'),
    path('contest/mark/confirm/<slug:level_name>/', views.AnswerMarkConfirm.as_view(), name='answer_mark_confirm'),
    path('contest/mark/done/<slug:level_name>/', views.AnswerMarkDone.as_view(), name='answer_mark_done'),
    path('contest/results/', views.ContestList.as_view(), name='contest_list'),
    path('contest/results/<int:contest_id>/', views.ContestDetail.as_view(), name='contest_detail'),
    path('contest/results/<int:contest_id>/<slug:level_name>/', views.MatchDetail.as_view(), name='match_detail'),
    path('gallery/', views.GalleryTop.as_view(), name='gallery_top'),
    path('gallery/<int:answer_id>/', views.GalleryDetail.as_view(), name='gallery_detail'),
    path('question/post/', views.QuestionPost.as_view(), name='question_post'),
    path('question/check/', views.QuestionCheck.as_view(), name='question_check'),

    #path('api/ajax-post-search/', views.ajax_post_search, name='ajax_post_search'),
    path('api/post-favorite/', views.api.post_favorite, name='api_post_favorite'),
    path('api/post-comment/', views.api.post_comment, name='api_post_comment'),
    #path('api/ajax-sort-answer/', views.ajax_sort_answer, name='ajax_sort_answer'),
    path('api/check-question/', views.api.check_question, name='api_check_question'),
]

common/urls.py
from django.urls import path

from . import views


app_name = 'common'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('signup/done/', views.UserCreateDone.as_view(), name='signup_done'),
    path('signup/complete/<str:token>/', views.UserCreateComplete.as_view(), name='signup_complete'),
    path('settings/', views.UserSettingsList.as_view(), name='user_settings_list'),
    path('settings/update/', views.user_settings_update, name='user_settings_update'),
    path('password/change/', views.PasswordChange.as_view(), name='password_change'),
    path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<username>/', views.UserDetail.as_view(), name='user_detail'),

    path('api/icon-upload/', views.api.icon_upload, name='api_icon_upload'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('classic/', include('classic.urls')),
    path('scramble/', include('scramble.urls')),
    path('', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classic/views/answer.py
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, RedirectView, UpdateView
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import Http404

from classic.models import Question, Answer, Contest, Match
from classic.forms import AnswerForm


User = get_user_model()

class AnswerPost(LoginRequiredMixin, CreateView):
    '''
    クラスベースビューで書こうとしたらこうなる
    '''
    model = Answer
    form_class = AnswerForm
    template_name = 'classic/answer_post.html'
    success_url = reverse_lazy('classic:answer_edit')


    def setup(self, request, *args, **kwargs):
        """Initialize attributes shared by all view methods."""
        super().setup(request, *args, **kwargs)
        self.kwargs['match'] = get_object_or_404(
            Match,
            contest__is_held=True,
            contest__is_asked=True,
            contest__date_asked__lte=timezone.now(),
            contest__post_deadline__gte=timezone.now(),
            level=request.user.profile.classic_level,
        )

    def dispatch(self, request, *args, **kwargs):
        # Try to dispatch to the right method; if a method doesn't exist,
        # defer to the error handler. Also defer to the error handler if the
        # request method isn't on the approved list.
        # 一度答えている場合は編集画面にリダイレクトする
        if User.objects.filter(
            pk=request.user.id,
            answer__match=self.kwargs['match']
        ).exists():
            return redirect('classic:answer_edit')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.panellist = self.request.user
        form.instance.match = self.kwargs['match']
        messages.success(self.request, "回答を投稿しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        # バリデーションに失敗した時
        messages.warning(self.request, "回答を投稿できませんでした")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        """Insert match into the context dict."""
        if 'match' not in kwargs:
            kwargs['match'] = self.kwargs['match']
        return super().get_context_data(**kwargs)


class AnswerEdit(LoginRequiredMixin, UpdateView):
    '''
    クラスベースビューで書こうとしたらこうなる
    '''
    model = Answer
    form_class = AnswerForm
    template_name = 'classic/answer_edit.html'
    success_url = reverse_lazy('classic:index')

    def form_valid(self, form):
        messages.success(self.request, "回答を投稿しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        # バリデーションに失敗した時
        messages.warning(self.request, "回答を投稿できませんでした")
        return super().form_invalid(form)

    def get_object(self, queryset=None):
        answer = get_object_or_404(
            Answer,
            match__contest__is_held=True,
            match__contest__is_asked=True,
            match__contest__date_asked__lte=timezone.now(),
            match__contest__post_deadline__gte=timezone.now(),
            match__level=self.request.user.profile.classic_level,
            panellist=self.request.user,
        )
        return answer

classic/views/answer_review.py
import enum
import math
from pipes import Template
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView, DetailView, RedirectView, UpdateView, FormView
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.utils.decorators import method_decorator
from django.db.models import F, Q

from classic.models import Question, Answer, Contest, Match, Level, AnswerReview
from classic.forms import AnswerForm, create_DynamicAnswerReviewForm


User = get_user_model()

class AnswerMarkTop(TemplateView):
    template_name = 'classic/answer_mark_top.html'

    def get_context_data(self, **kwargs):
        """Insert match into the context dict."""
        context = super().get_context_data(**kwargs)
        contest = get_object_or_404(
            Contest,
            is_held=True,
            is_marked=True,
            post_deadline__lte=timezone.now(),
            date_marked__gte=timezone.now(),
        )
        match_list = Match.objects.filter(
            contest=contest
        ).order_by('level__order')
        context.update({
            'contest': contest,
            'match_list': match_list,
        })
        return context


class AnswerMarkPost(LoginRequiredMixin, FormView):
    '''
        contestに紐づくanswers採点入力フォーム
    '''
    template_name = 'classic/answer_mark_post.html'


    def dispatch(self, request, *args, **kwargs):
        # Try to dispatch to the right method; if a method doesn't exist,
        # defer to the error handler. Also defer to the error handler if the
        # request method isn't on the approved list.
        # 自分が答えている場合は採点top画面にリダイレクトする
        match = self.kwargs['match']
        if User.objects.filter(
            pk=request.user.id,
            answer__match=match
        ).exists():
            messages.info(request, "自分が参加しているマッチの採点はできません")
            return redirect('classic:answer_mark_top')
        # 一度採点している場合は採点決定画面にリダイレクトする
        if User.objects.filter(
            pk=request.user.id,
            answer_review__answer__match=match
        ).exists():
            return redirect('classic:answer_mark_done', match.level.name)

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        match = self.kwargs['match']
        self.request.session[f'mark_form_data_{match.id}'] = form.cleaned_data
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "採点を保存できませんでした")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        """Insert match into the context dict."""
        context = super().get_context_data(**kwargs)
        context.update({
            'match': self.kwargs['match'],
            'question': Question.objects.filter(
                was_checked=False
            ).exclude(
                Q(questioner=self.request.user) |
                Q(question_check__checker=self.request.user)
            ).order_by(
                'id'
            ).first()
        })
        return context

    def get_form_class(self):
        match = self.kwargs['match']
        return create_DynamicAnswerReviewForm(match.id)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.method == 'GET':
            match = self.kwargs['match']
            kwargs['data'] = self.request.session.get(f'mark_form_data_{match.id}')
        return kwargs

    def get_success_url(self):
        return reverse('classic:answer_mark_confirm', kwargs={'level_name': self.kwargs.get('level_name')})

    def setup(self, request, *args, **kwargs):
        """Initialize attributes shared by all view methods."""
        super().setup(request, *args, **kwargs)
        level = get_object_or_404(
            Level,
            name=self.kwargs.get('level_name'),
        )
        self.kwargs['match'] = get_object_or_404(
            Match,
            contest__is_held=True,
            contest__is_marked=True,
            contest__post_deadline__lte=timezone.now(),
            contest__date_marked__gte=timezone.now(),
            level=level,
        )


class AnswerMarkConfirm(LoginRequiredMixin, FormView):
    '''
        contestに紐づくanswers採点確認フォーム
    '''
    template_name = 'classic/answer_mark_confirm.html'
    success_url = reverse_lazy('classic:answer_mark_top')

    def dispatch(self, request, *args, **kwargs):
        # 自分が答えている場合は採点top画面にリダイレクトする
        match = self.kwargs['match']
        if User.objects.filter(
            pk=request.user.id,
            answer__match=match
        ).exists():
            messages.info(request, "自分が参加しているマッチの採点はできません")
            return redirect('classic:answer_mark_top')
        # 一度採点している場合は採点決定画面にリダイレクトする
        if User.objects.filter(
            pk=request.user.id,
            answer_review__answer__match=match
        ).exists():
            messages.info(request, "すでに採点が済んでいます")
            return redirect('classic:answer_mark_done', match.level.name)
        # セッション切れや、セッションが空でURL直接入力したら入力画面にリダイレクト
        if self.kwargs['form_data'] is None:
            return redirect('classic:answer_mark_top')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        match = self.kwargs['match']
        form_data = self.kwargs['form_data']
        answer_list = Answer.objects.filter(match=match)
        for answer in answer_list:
            answer_review = AnswerReview.objects.create(
                answer=answer,
                reviewer=self.request.user,
                point=form_data[f'point_{answer.id}'],
                # comment=form_data[f'comment_{answer.id}']
            )
            answer.score = F('score') + answer_review.point
            answer.save()
        for index, answer in enumerate(answer_list.order_by('-score')):
            answer.rank = index + 1
            answer.save()
        self.request.session.pop(f'mark_form_data_{match.id}')
        messages.success(self.request, "採点を完了しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, "採点を保存できませんでした")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        """Insert match into the context dict."""
        context = super().get_context_data(**kwargs)
        context['match'] = self.kwargs['match']
        return context

    def get_form_class(self):
        match = self.kwargs['match']
        return create_DynamicAnswerReviewForm(match.id)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.method in ('GET', 'POST', 'PUT'):
            match = self.kwargs['match']
            kwargs.update({
                'data': self.request.session.get(f'mark_form_data_{match.id}')
            })
        return kwargs

    def setup(self, request, *args, **kwargs):
        """Initialize attributes shared by all view methods."""
        super().setup(request, *args, **kwargs)
        level = get_object_or_404(
            Level,
            name=self.kwargs.get('level_name'),
        )
        match = get_object_or_404(
            Match,
            contest__is_held=True,
            contest__is_marked=True,
            contest__post_deadline__lte=timezone.now(),
            contest__date_marked__gte=timezone.now(),
            level=level,
        )
        self.kwargs['match'] = match
        self.kwargs['form_data'] = request.session.get(f'mark_form_data_{match.id}')


class AnswerMarkDone(LoginRequiredMixin, DetailView):
    template_name = 'classic/answer_mark_done.html'

    def dispatch(self, request, *args, **kwargs):
        # 自分が答えている場合は採点top画面にリダイレクトする
        match = self.kwargs['match']
        if User.objects.filter(
            pk=request.user.id,
            answer__match=match
        ).exists():
            messages.info(request, "自分が参加しているマッチの採点はできません")
            return redirect('classic:answer_mark_top')
        # 採点が済んでいない場合は採点入力画面にリダイレクトする
        if not User.objects.filter(
            pk=request.user.id,
            answer_review__answer__match=match
        ).exists():
            messages.info(request, "まだ採点が済んでいません")
            return redirect('classic:answer_mark_post', match.level.name)

        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.kwargs['match']

    def setup(self, request, *args, **kwargs):
        """Initialize attributes shared by all view methods."""
        super().setup(request, *args, **kwargs)
        level = get_object_or_404(
            Level,
            name=self.kwargs.get('level_name'),
        )
        match = get_object_or_404(
            Match,
            contest__is_held=True,
            contest__is_marked=True,
            contest__post_deadline__lte=timezone.now(),
            contest__date_marked__gte=timezone.now(),
            level=level,
        )
        self.kwargs['match'] = match

classic/views/gallery.py
from classic.models import Question, Answer
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect, get_object_or_404


# Create your views here.
class GalleryTop(ListView):
    template_name = 'classic/gallery_top.html'
    queryset = Answer.objects.filter(
        match__contest__was_marked=True,
    )


class GalleryDetail(DetailView):
    # model = Answer
    template_name = 'classic/gallery_detail.html'
    pk_url_kwarg = 'answer_id'
    queryset = Answer.objects.filter(
        match__contest__was_marked=True,
    )

classic/views/index.py
from django.views import generic


# Create your views here.
class Index(generic.TemplateView):
    template_name = 'classic/index.html'

templates/classic/answer_edit.html
{% extends 'base.html' %}

{% block content %}
    {{ answer.match.question.text }}
    {% if answer.match.question.image %}
        <img src="{{ answer.match.question.image.url }}" class="img-fluid" alt="お題画像">
    {% endif %}

    <form method="POST">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">保存</button>
    </form>
{% endblock %}

templates/classic/answer_mark_confirm.html
{% extends 'base.html' %}

{% load widget_tweaks %}


{% block content %}
    {{ match.question.text }}
    {% if match.question.image %}
        <img src="{{ match.question.image.url }}" class="img-fluid" alt="お題画像">
    {% endif %}

    {% for field in form %}
    <div class="mb-3">
        {% if field.label %}<!--得点欄-->
            <p>{{ field.label }}</p>
            <div class="btn-group" role="group" aria-label="radio button group">
                {{ field.value }}
            </div>
        {% else %}<!--コメント欄-->
            {{ field.value }}
        {% endif %}
        {{ field.errors }}
    </div>
    {% endfor %}
    <a href="{% url 'classic:answer_mark_post' match.level.name %}" class="btn btn-primary">戻る</a>
    <hr>
    <form action="" method="POST">
        <button type="submit" class="btn btn-primary">保存</button>
        {% csrf_token %}
    </form>
{% endblock %}

templates/classic/answer_mark_done.html
{% extends 'base.html' %}

{% load widget_tweaks %}


{% block content %}
    {{ match.question.text }}
    {% if match.question.image %}
        <img src="{{ match.question.image.url }}" class="img-fluid" alt="お題画像">
    {% endif %}

    <div class="d-grid gap-0">
        現在の順位
        {% for answer in match.answers.all|dictsort:"rank" %}
            <a href="{% url 'common:user_detail' answer.panellist.username %}" class="d-block border-bottom p-2">
                {{ answer.rank }}位
                {{ answer.score }}点
                <span class="m-2">
                    <img src="{{ answer.panellist.profile.icon.url }}" class="rounded-circle" height="35px" width="35px" alt="アイコン">
                </span>
                {{ answer.panellist.account_name }}
            </a>
        {% endfor %}
    </div>

    {% for answer in match.answers.all %}
    <div>
        {{ answer.text }}
        <div>
            {% for answer_review in answer.answer_reviews.all %}
                {% if answer_review.reviewer == user %}
                    {{ answer_review.point }}
                {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endfor %}
{% endblock %}

templates/classic/answer_mark_post.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}


{% block content %}
    <!-- Modal -->
    {% if question %}
        {% include 'classic/includes/question_check_modal.html' %}
    {% endif %}

    <h5>{{ match.question }}</h5>
    <div class="mb-2">
        {% if match.question.image %}
            <img src="{{ match.question.image.url }}" class="img-fluid" alt="お題画像">
        {% endif %}
    </div>

    <form method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="mb-3">
            <p>{{ field.label }}</p>
            <div class="btn-group" role="group" aria-label="radio button group">
                {% for radio in field %}
                    {{ radio.tag }}
                    <label for="{{ radio.id_for_label }}" class="btn btn-outline-primary">
                        {{ radio.choice_label }}
                    </label>
                {% endfor %}
            </div>
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">保存</button>
    </form>
{% endblock %}

{% block extrajs %}
    <script src="{% static 'classic/js/check_question.js' %}"></script>
{% endblock %}

templates/classic/answer_mark_top.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h4 class="mb-3">第{{contest.id}}回</h4>

    <div class="row">
        {% for match in match_list %}
            <div class="col-lg-6 mb-4">
                <div class="card shadow h-100 d-flex flex-row">
                    <div class="">
                        <span class="">{{ match.level }}</span>
                    </div>
                    <div class="card-body d-flex flex-column">
                        <a href="{% url 'classic:answer_mark_post' match.level.name %}">
                            {{ match.question.text }}
                        </a>
                        {% if match.question.image %}
                            <div>
                                <img src="{{ match.question.image.url }}" alt="お題画像">
                            </div>
                        {% endif %}
                        <div class="">
                            {% for answer in match.answers.all %}
                                <a href="{% url 'common:user_detail' answer.panellist.username %}" class="btn btn-light btn-sm">
                                    <img src="{{ answer.panellist.profile.icon.url }}" class="img-profile-sm" alt="アイコン">
                                    <span class="small">{{ answer.panellist.account_name }}</span>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            お題がありません
        {% endfor %}
    </div>

{% endblock %}

templates/classic/answer_post.html
{% extends 'base.html' %}

{% block content %}
    {{ match.question.text }}
    {% if match.question.image %}
        <img src="{{ match.question.image.url }}" class="img-fluid" alt="お題画像">
    {% endif %}

    <form method="POST">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">保存</button>
    </form>
{% endblock %}

templates/classic/contest_list.html
{% extends 'base.html' %}

{% block content %}
    {% for contest in contest_list %}
        <div class="card">
            <div class="card-header">
                <a href="{% url 'classic:contest_detail' contest.id %}">第{{contest.id}}回</a>
            </div>
            <div class="accordion accordion-flush" id="accordionFlush{{contest.id}}">
                {% for match in contest.matches.all|dictsort:"level.order" %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-heading{{contest.id}}-{{match.level}}">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{contest.id}}-{{match.level}}" aria-expanded="false" aria-controls="flush-collapse{{contest.id}}-{{match.level}}">
                                <span class="">{{ match.level }}</span>
                                {{ match.question.text }}
                                {% if match.question.image %}
                                    <div>
                                        <img src="{{ match.question.image.url }}" alt="お題画像">
                                    </div>
                                {% endif %}
                            </button>
                        </h2>
                        <div id="flush-collapse{{contest.id}}-{{match.level}}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{contest.id}}-{{match.level}}" data-bs-parent="#accordionFlush{{contest.id}}">
                            <div class="accordion-body">
                                <div class="list-group list-group-flush">
                                    {% for answer in match.answers.all|dictsort:"rank"|slice:":3" %}
                                        <a href="#" class="list-group-item list-group-item-action">
                                            <p class="mb-1">
                                                <span class="">{{ answer.rank }}</span>
                                                {{ answer.text }}
                                            </p>
                                            <small>
                                                <img src="{{ answer.panellist.profile.icon.url }}" class="rounded-circle img-thumbnail" height="24px" width="24px" alt="アイコン">
                                                {{ answer.panellist.account_name }}
                                            </small>
                                        </a>
                                    {% endfor %}
                                </div>
                                <a href="{% url 'classic:match_detail' contest.id match.level.name %}" class="btn btn-primary">他の回答も見る</a>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="card-body">
                        <div class="card-text">
                            お題がありません
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% empty %}
        <div>お題がありません</div>
    {% endfor %}
{% endblock %}

templates/classic/gallery_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'classic/includes/answer_card_detail.html' %}
{% endblock %}

{% block extrajs %}
    <script src="{% static 'classic/js/favorite.js' %}"></script>
    <script src="{% static 'classic/js/post_comment.js' %}"></script>
{% endblock %}

templates/classic/gallery_top.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
    {% for answer in answer_list %}
        {% include 'classic/includes/answer_card.html' %}
    {% empty %}
        <p>お題がありません</p>
    {% endfor %}
{% endblock %}

{% block extrajs %}
    <script src="{% static 'classic/js/favorite.js' %}"></script>
{% endblock %}

templates/classic/index.html
{% extends 'base.html' %}

{% block content %}
    classic index
    <a class="" href="{% url 'classic:contest_redirect'%}">
        コンテスト
    </a>
    <a class="" href="{% url 'classic:contest_list'%}">
        コンテスト結果
    </a>
    <a class="" href="{% url 'classic:gallery_top'%}">
        ギャラリー
    </a>
{% endblock %}

{% block extrajs %}
    <script>
        const navItem = document.getElementById('classicNav');
        navItem.querySelector('.nav-link').classList.add('active');
        navItem.querySelector('.nav-link').setAttribute('aria-expanded', 'true');
        navItem.querySelector('.nav-link').setAttribute('aria-current', 'page');
        navItem.querySelector('.collapse').classList.add('show');
        navItem.querySelector('.collapse .collapse-inner .home').classList.add('active');
    </script>
{% endblock %}

templates/classic/question_check.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
    <!-- Modal -->
    {% if question %}
        {% include 'classic/includes/question_check_modal.html' %}
        <div class="card shadow">
            <div class="card-header p-3">
                <div class="text-muted">
                    お題の評価にご協力ください
                </div>
            </div>
            <div class="card-body">
                <div class="card-text">
                    {{ question.text }}
                </div>
                <div id="check-question-image">
                    {% if question.image %}
                        <img src="{{ question.image.url }}" class="img-fluid" alt="お題画像">
                    {% endif %}
                </div>
            </div>
            <div class="card-footer bg-transparent">
                <div class="container-fluid">
                    <form id="form-check-question" action="{% url 'classic:api_check_question' %}" method="POST">
                        {% csrf_token %}
                        <div class="d-flex justify-content-evenly">
                            <button type="submit" class="btn btn-primary" name="question-check-{{question.id}}" value="0" >
                                <span class="pe-1">
                                    <i class="bi bi-hand-thumbs-up-fill"></i>
                                </span>
                                いいね！
                            </button>
                            <button type="submit" class="btn btn-secondary" name="question-check-{{question.id}}" value="1">
                                <span class="pe-1">
                                    <i class="bi bi-hand-thumbs-down-fill"></i>
                                </span>
                                う〜ん...
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block extrajs %}
    <script src="{% static 'classic/js/check_question.js' %}"></script>
{% endblock %}

templates/classic/question_post_form.html
{% extends "base.html" %}

{% load static %}

{% block extrastyle %}
{% endblock extrastyle %}



{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% include 'includes/form.html' %}
    <div class="img-question-container mb-3"></div>
    <button type="submit" class="btn btn-primary">保存</button>
</form>
{% endblock %}


{% block extrajs %}
    <script src="{% static 'classic/js/post_question.js' %}"></script>
{% endblock %}