classic/urls.py
from django.urls import path

from . import views


app_name = 'classic'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('contest/', views.ContestRedirect.as_view(), name='contest_redirect'),
    path('contest/answer/', views.AnswerPost.as_view(), name='answer_post'),
    path('contest/answer/edit/', views.AnswerEdit.as_view(), name='answer_edit'),
    path('contest/mark/', views.AnswerMarkTop.as_view(), name='answer_mark_top'),
    path('contest/mark/post/<slug:level_name>/', views.AnswerMarkPost.as_view(), name='answer_mark_post'),
    path('contest/mark/confirm/<slug:level_name>/', views.AnswerMarkConfirm.as_view(), name='answer_mark_confirm'),
    path('contest/mark/done/<slug:level_name>/', views.AnswerMarkDone.as_view(), name='answer_mark_done'),
    path('contest/results/', views.ContestList.as_view(), name='contest_list'),
    path('contest/results/<int:contest_id>/', views.ContestDetail.as_view(), name='contest_detail'),
    path('contest/results/<int:contest_id>/<slug:level_name>/', views.MatchDetail.as_view(), name='match_detail'),
    path('gallery/', views.GalleryTop.as_view(), name='gallery_top'),
    path('gallery/<int:answer_id>/', views.GalleryDetail.as_view(), name='gallery_detail'),
    path('question/post/', views.QuestionPost.as_view(), name='question_post'),
    path('question/check/', views.QuestionCheck.as_view(), name='question_check'),

    #path('api/ajax-post-search/', views.ajax_post_search, name='ajax_post_search'),
    path('api/post-favorite/', views.api.post_favorite, name='api_post_favorite'),
    path('api/post-comment/', views.api.post_comment, name='api_post_comment'),
    #path('api/ajax-sort-answer/', views.ajax_sort_answer, name='ajax_sort_answer'),
    path('api/check-question/', views.api.check_question, name='api_check_question'),
]

common/urls.py
from django.urls import path

from . import views


app_name = 'common'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('signup/done/', views.UserCreateDone.as_view(), name='signup_done'),
    path('signup/complete/<str:token>/', views.UserCreateComplete.as_view(), name='signup_complete'),
    path('settings/', views.UserSettingsList.as_view(), name='user_settings_list'),
    path('settings/update/', views.user_settings_update, name='user_settings_update'),
    path('password/change/', views.PasswordChange.as_view(), name='password_change'),
    path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<username>/', views.UserDetail.as_view(), name='user_detail'),

    path('api/icon-upload/', views.api.icon_upload, name='api_icon_upload'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('classic/', include('classic.urls')),
    path('scramble/', include('scramble.urls')),
    path('', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scramble/urls.py
from django.urls import path

from . import views


app_name = 'scramble'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

templates/includes/auth.html
{% load static %}
{% load widget_tweaks %}


<!doctype html>
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block style %}
            <!-- Bootstrap CSS -->
            <link rel="stylesheet" href="{% static 'lib/css/bootstrap.custom.css' %}">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">

            <!-- Font Family -->
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">

            <!-- my CSS-->
            <link rel="stylesheet" href="{% static 'common/css/auth.css' %}">
        {% endblock%}

        {% block extrastyle %}
        {% endblock%}

        <title>OGLeague</title>
    </head>
    <body class="bg-primary">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="card border-0 shadow-lg my-5">
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-lg-6 d-none d-lg-block bg-login-image">
                                </div>
                                <div class="col-lg-6">
                                    <div class="p-5">
                                        <div class="text-center">
                                            {% block header %}
                                            {% endblock header %}
                                        </div>
                                        {% block form %}
                                        {% endblock form %}

                                        {% block footer %}
                                        {% endblock footer %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {% block js %}
            <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        {% endblock %}

        {% block extrajs %}
        {% endblock %}
    </body>
</html>

templates/includes/form.html
{% load widget_tweaks %}


{% if form.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %}
            {{ error }}<br>
        {% endfor %}
    </div>
{% endif %}

{% for field in form %}
    <div class="mb-3">
        {{ field |add_label_class:'form-label' }}
        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">
                {{ field.help_text }}
            </small>
        {% endif %}
    </div>
{% endfor %}

{% csrf_token %}

templates/includes/form_floating_labels.html
{% load widget_tweaks %}


{% if form.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %}
            {{ error }}<br>
        {% endfor %}
    </div>
{% endif %}

{% for field in form %}
    <div class="mb-3">
        {% if form.is_bound %}
            {% if field.errors or form.non_field_errors %}
                <div class="form-floating">
                    {% render_field field class="form-control is-invalid" placeholder=field.label %}
                    {{ field |add_label_class:'form-label' }}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>

            {% else %}
                <div class="form-floating">
                    {% render_field field class="form-control is-valid" placeholder=field.label %}
                    {{ field |add_label_class:'form-label' }}
                </div>
            {% endif %}
        {% else %}
            <div class="form-floating">
                {% render_field field class="form-control" placeholder=field.label %}
                {{ field |add_label_class:'form-label' }}
            </div>
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">
                {{ field.help_text }}
            </small>
        {% endif %}
    </div>
{% endfor %}

{% csrf_token %}

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
            <span class="me-2">
                {% if message.tags == "success" %}
                    <i class="bi bi-check-circle-fill"></i>
                {% elif message.tags == "info" %}
                    <i class="bi bi-info-circle-fill"></i>
                {% elif message.tags == "danger" or message.tags == "warning" or message.tags == "dark" %}
                    <i class="bi bi-exclamation-triangle-fill"></i>
                {% endif %}
            </span>
            <span class="">{{ message | safe }}</span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
{% load static %}


<nav class="navbar navbar-expand navbar-light bg-white topbar shadow mb-4">
    <div class="container-fluid">
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle me-2">
            <i class="bi bi-list"></i>
        </button>
        <a class="navbar-brand" href="{% url 'common:index' %}">OGLeague</a>

        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.profile.icon.url }}" class="img-profile rounded-circle" alt="アイコン">
                        <span class="d-none d-md-inline ms-1 small">{{ user.account_name }}</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'common:user_detail' user.username %}">
                                <span class=" me-2"><i class="bi bi-person-fill"></i></span>プロフィール
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'common:user_settings_list' %}">
                                <span class="me-2"><i class="bi bi-gear-fill"></i></span>設定
                            </a>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="{% url 'common:logout' %}">
                                <span class="me-2"><i class="bi bi-box-arrow-right"></i></span>ログアウト
                            </a>
                        </li>
                    </ul>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:login' %}">
                        <i class="bi bi-box-arrow-in-left"></i>
                        <span class="ms-1">ログイン</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div><!-- /.container-fluid -->
</nav>

templates/includes/sidebar.html
<ul id="sidebar" class="navbar-nav bg-primary bg-gradient">
    <li class="nav-item" id="classicNav">
        <a class="nav-link" data-bs-toggle="collapse" href="#collapseClassic" role="button" aria-expanded="false" aria-controls="collapseClassic">
            <span>CL</span>
            <span>クラシック</span>
        </a>
        <div class="collapse" id="collapseClassic" data-bs-parent="#sidebar">
            <div class="collapse-inner rounded">
                <a href="{% url 'classic:index' %}" class="collapse-item home">
                    ホーム
                </a>
                <a href="{% url 'classic:contest_redirect' %}" class="collapse-item contest">
                    コンテスト
                </a>
                <a href="{% url 'classic:gallery_top' %}" class="collapse-item gallery">
                    ギャラリー
                </a>
                <hr>
                <a href="{% url 'classic:question_post' %}" class="collapse-item post">
                    お題投稿
                </a>
                <a href="{% url 'classic:question_check' %}" class="collapse-item check">
                    お題チェック
                </a>
            </div>
        </div>
    </li>

    <li class="nav-item" id="scrambleNav">
        <a class="nav-link" data-bs-toggle="collapse" href="#collapseScramble" role="button" aria-expanded="false" aria-controls="collapseScramble">
            <span>SC</span>
            <span>スクランブル</span>
        </a>
        <div class="collapse" id="collapseScramble" data-bs-parent="#sidebar">
            <div class="collapse-inner rounded">
                <a href="{% url 'scramble:index' %}" class="collapse-item home">
                    ホーム
                </a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{% url 'common:user_list' %}">
            <i class="bi bi-people-fill"></i>
            <span>ユーザー</span>
        </a>
    </li>

</ul>

templates/includes/topbar.html
{% load static %}


<nav id="topbar" class="navbar navbar-expand navbar-light bg-white">
    <div class="container-fluid">
        <button id="sidebarToggleTop" class="btn btn-link rounded-circle me-2">
            <i class="bi bi-list"></i>
        </button>
        <a class="navbar-brand" href="{% url 'common:index' %}">OGLeague</a>

        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.profile.icon.url }}" class="img-profile" alt="アイコン">
                        <span class="d-none d-md-inline ms-1 small">{{ user.account_name }}</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'common:user_detail' user.username %}">
                                <span class=" me-2"><i class="bi bi-person-fill"></i></span>プロフィール
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'common:user_settings_list' %}">
                                <span class="me-2"><i class="bi bi-gear-fill"></i></span>設定
                            </a>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="{% url 'common:logout' %}">
                                <span class="me-2"><i class="bi bi-box-arrow-right"></i></span>ログアウト
                            </a>
                        </li>
                    </ul>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:login' %}">
                        <i class="bi bi-box-arrow-in-left"></i>
                        <span class="ms-1">ログイン</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div><!-- /.container-fluid -->
</nav>