common/urls.py
from django.urls import path

from . import views


app_name = 'common'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('signup/done/', views.UserCreateDone.as_view(), name='signup_done'),
    path('signup/complete/<str:token>/', views.UserCreateComplete.as_view(), name='signup_complete'),
    path('settings/', views.UserSettingsList.as_view(), name='user_settings_list'),
    path('settings/update/', views.user_settings_update, name='user_settings_update'),
    path('password/change/', views.PasswordChange.as_view(), name='password_change'),
    path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<username>/', views.UserDetail.as_view(), name='user_detail'),

    path('api/icon-upload/', views.api.icon_upload, name='api_icon_upload'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('classic/', include('classic.urls')),
    path('scramble/', include('scramble.urls')),
    path('', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models/profile.py
from django.db import models
from django.contrib.auth import get_user_model
from django.apps import apps


Level = apps.get_model('classic', 'Level', require_ready=False)
User = get_user_model()

def get_or_create_default_level():
    default_level, created = Level.objects.get_or_create(
        name='C',
        order=4
    )
    return default_level

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    icon = models.ImageField(
        verbose_name="アイコン",
        upload_to='image/common/user_icon/',
        default='image/common/user_icon/hiyokko.png'
    )
    bio = models.CharField(
        '自己紹介',
        blank = True,
        max_length=140,
        help_text='最大140文字です。',
    )
    classic_level = models.ForeignKey(
        Level,
        verbose_name="レベル",
        on_delete=models.PROTECT,
        default=get_or_create_default_level,
        related_name="users",
        related_query_name="user",
    )

    class Meta:
        verbose_name = "プロフィール"
        verbose_name_plural = "プロフィール"
        ordering = ['classic_level', ]

    def __str__(self):
        return self.user.username

common/views/email.py
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.core.mail import send_mail
from django.http import HttpResponseBadRequest
from django.template.loader import render_to_string
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from common.forms import EmailChangeForm


class EmailChange(LoginRequiredMixin, generic.FormView):
    '''メールアドレスの変更'''
    template_name = 'common/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data['email']

        # URLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }

        subject = render_to_string('common/mail/email_change/subject.txt', context)
        message = render_to_string('common/mail/email_change/message.txt', context)
        send_mail(subject, message, None, [new_email])

        return redirect('common:email_change_done')


class EmailChangeDone(LoginRequiredMixin, generic.TemplateView):
    '''メールアドレスの変更メールを送ったよ'''
    template_name = 'common/email_change_done.html'


class EmailChangeComplete(LoginRequiredMixin, generic.TemplateView):
    '''リンクを踏んだ後に呼ばれるメアド変更ビュー'''
    template_name = 'common/email_change_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60)  # デフォルトでは1時間以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは間違いなし
        else:
            # User.objects.get(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)

common/views/index.py
from django.views import generic


class Index(generic.TemplateView):
    """トップページ"""
    template_name = 'common/index.html'

common/views/password.py
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)

from ..forms import (
    MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm
)


class PasswordChange(PasswordChangeView):
    '''パスワード変更ビュー'''
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('common:password_change_done')
    template_name = 'common/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    '''パスワード変更しました'''
    template_name = 'common/password_change_done.html'


class PasswordReset(PasswordResetView):
    '''パスワード忘れた人に変更用URLの送付ページ'''
    subject_template_name = 'common/mail/password_reset/subject.txt'
    email_template_name = 'common/mail/password_reset/message.txt'
    template_name = 'common/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('common:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    '''パスワード忘れた人に変更用URLを送りましたページ'''
    template_name = 'common/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    '''パスワード忘れた人が新パスワード入力ページ'''
    form_class = MySetPasswordForm
    success_url = reverse_lazy('common:password_reset_complete')
    template_name = 'common/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    '''パスワード忘れた人が新パスワード設定しましたページ'''
    template_name = 'common/password_reset_complete.html'

common/views/user.py
from django.conf import settings
from django.shortcuts import redirect, resolve_url, render, get_object_or_404
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.template.loader import render_to_string
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

from common.forms import MyUserCreationForm, UserUpdateForm, ProfileUpdateForm

from classic.models import Answer, Level


User = get_user_model()


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'common/signup.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('common/mail/signup/subject.txt', context)
        message = render_to_string('common/mail/signup/message.txt', context)

        user.email_user(subject, message)
        return redirect('common:signup_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録した後の画面"""
    template_name = 'common/signup_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'common/signup_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60)  # デフォルトでは1時間以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    login(request, user)
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class UserSettingsList(LoginRequiredMixin, generic.TemplateView):
    template_name = 'common/user_settings_list.html'


class UserSettingsUpdate(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'common/user_settings_form.html'

    def get_success_url(self):
        return resolve_url('common:user_settings_list')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        ''' バリデーションを通った時 '''
        messages.success(self.request, "ユーザー情報を更新しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        ''' バリデーションに失敗した時 '''
        messages.warning(self.request, "ユーザー情報を更新できませんでした")
        return super().form_invalid(form)


@login_required
def user_settings_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            messages.success(request, "ユーザー情報を更新しました")
            return redirect('common:user_settings_update')
        else:
            messages.warning(request, "ユーザー情報を更新できませんでした")

    # GETのとき
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile) # 既に保存してあるデータを引っ張ってきてformをテンプレートへ渡す

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'common/user_settings_form.html', context)


class UserList(generic.ListView):
    '''ユーザー一覧'''
    model = User
    ordering = ('profile', 'username', )
    paginate_by = 15
    template_name = 'common/user_list.html'
    # context_object_name = 'player_list'
    # queryset = User.objects.order_by('username')

# class UserList(generic.TemplateView):
    # '''ユーザー一覧'''
    # template_name = 'common/user_list.html'

    # def get_context_data(self, **kwargs):
        # """Insert match into the context dict."""
        # context = super().get_context_data(**kwargs)
        # player_list = {}
        # for level in Level.objects.order_by('order'):
            # player_list[level] = User.objects.filter(
                # profile__classic_level=level
            # ).order_by('username')
        # context['player_list'] = player_list
        # return context

class UserDetail(generic.DetailView):
    context_object_name = 'player'
    model = User
    template_name = 'common/user_detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answer_list'] = Answer.objects.filter(
            panellist=self.object,
            match__contest__was_marked=True
        ).order_by('-date_answered')
        return context

templates/common/email_change_complete.html
{% extends "base.html" %}

{% block content %}
<p>
    メールアドレスを変更しました。<br>
</p>
<a class="btn btn-primary" href="{% url 'common:index' %}">トップページ</a>
{% endblock %}

templates/common/email_change_done.html
{% extends "base.html" %}

{% block content %}
<p>
    確認メールに記載されているリンクをクリックすると、アドレスが変更されます。
</p>
{% endblock %}

templates/common/index.html
{% extends 'base.html' %}


{% block content %}
    <p>Hi there!</p>
    <p>It works!</p>
    <p>common</p>
{% endblock %}

templates/common/password_change.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
    {% include 'includes/form_floating_labels.html' %}
    <button type="submit" class="btn btn-primary">保存</button>
</form>
{% endblock %}

templates/common/password_change_done.html
{% extends "base.html" %}

{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary" href="{% url 'common:index' %}">トップページ</a>
</p>
{% endblock %}

templates/common/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
<p>
    パスワード再設定を完了しました。<br>
    <a class="btn btn-primary" href="{% url 'common:login' %}">ログイン</a>
</p>
{% endblock %}

templates/common/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<p>
    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。
</p>
{% endblock %}

templates/common/password_reset_form.html
{% extends 'includes/auth.html' %}

{% block header %}
    <h4 class="mb-2">
        パスワードの再設定
    </h4>
    <p class="mb-4">
        ご登録されているメールアドレスにパスワードを再設定するためのリンクを送付いたします．
    </p>
{% endblock header %}

{% block form %}
    <form action="{% url 'common:password_reset' %}" method="POST">
        {% include 'includes/form_floating_labels.html' %}
        <div class="d-grid">
            <button type="submit" class="btn btn-primary" >
                保存
            </button>
        </div>
    </form>
{% endblock form %}

{% block footer %}
    <hr>
    <div class="text-center">
        <a href="{% url 'common:login' %}" class="small">ログイン</a>
    </div>
    <div class="text-center">
        <a href="{% url 'common:signup' %}" class="small">新規会員登録</a>
    </div>
{% endblock footer %}

templates/common/signup_complete.html
{% extends "base.html" %}

{% block content %}
<p>
    {{ user.username }}様 本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary" href="{% url 'common:index' %}">トップページ</a>
</p>
{% endblock %}

templates/common/signup_done.html
{% extends "base.html" %}

{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
</p>
{% endblock %}

templates/common/user_detail.html
{% extends "base.html" %}

{% load static %}


{% block content %}
    <div class="card justify-content-center shadow mb-4">
        <div class="card-body">
            <div class="d-flex align-items-center mb-3">
                <div class="flex-shrink-0">
                    <img src="{{ player.profile.icon.url }}" class="img-profile-lg" alt="アイコン">
                </div>
                <div class="flex-grow-1 ms-3">
                    <div class="username-wrapper mb-3">
                        <h5 class="card-title">{{ player.account_name }}</h5>
                        <h6 id="username" class="card-subtitle text-muted" data-username="{{player.username}}">@{{ player.username }}</h6>
                    </div>
                    {% if user == player %}
                        <a href="{% url 'common:user_settings_update' %}" class="card-link btn btn-outline-secondary btn-sm">
                            <span class="me-1"><i class="bi bi-person-fill"></i></span>プロフィールを変更
                        </a>
                    {% endif %}
                </div>
            </div>
            <div>
                {{ player.profile.classic_level }}レベル
            </div>
            <p class="card-text">{{ player.profile.bio|linebreaksbr }}</p>
        </div>
    </div>

    {% comment "" %}
        <div class="mb-3">
            <div class="row g-0">
                <div class="col">
                    <select class="sort-answer form-select" name="sort-answer" aria-label="answer sort">
                        <option value="date_answered">全て</option>
                        <option value="rank">1位</option>
                        <option value="score">高得点</option>
                        <option value="favorite">お気に入られ</option>
                    </select>
                </div>
                <div class="col">
                    <span class="">お気に入り</span>
                </div>
            </div>
        </div>
    {% endcomment %}

    <div id="sort-answer-result" class="d-grid gap-2">
        {% for answer in answer_list %}
            {% include 'classic/includes/answer_card.html' %}
        {% endfor %}
    </div>
{% endblock %}


{% block extrajs %}
    <script src="{% static 'classic/js/favorite.js' %}"></script>
    <script src="{% static 'classic/js/post_comment.js' %}"></script>
{% endblock %}

templates/common/user_list.html
{% extends 'base.html' %}

{% load static %}



{% block content %}
    <h4>
        ユーザー一覧
    </h4>
    <h5 class="mb-4">
        クラシック
    </h5>

    {% regroup page_obj.object_list by profile.classic_level as player_list %}

    <div class="list-group shadow bg-white rounded mb-4">
        {% for level in player_list %}
            <div class="list-group-item">
                <div class="bg-gradient">
                    {{ level.grouper }}
                </div>
            </div>
            {% for player in level.list %}
                <a href="{% url 'common:user_detail' player.username %}" class="list-group-item list-group-item-action d-flex align-items-center p-2">
                    <div class="me-2">
                        <img src="{{ player.profile.icon.url }}" class="img-profile" alt="アイコン">
                    </div>
                    <div class="me-auto">
                        {{ player.account_name }}
                    </div>
                    <div class="badge rounded-pill bg-warning me-1">
                        {{ player.profile.classic_level }}レベル
                    </div>
                    {% if player.answers.exists %}
                        <div class="badge rounded-pill bg-black">
                            <i class="bi bi-trophy-fill"></i>
                            {{ player.answers.count }}
                        </div>
                    {% endif %}
                </a>
            {% endfor %}
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
            {% endif %}

            <span class="current">
                {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}ページ
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">次へ</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

templates/common/user_settings_form.html
{% extends "base.html" %}


{% load static %}
{% load widget_tweaks %}


{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'croppie/croppie.css' %}"/>
{% endblock%}


{% block content %}
<form method="POST" enctype="multipart/form-data">

    <!-- Modal -->
    <div class="modal fade" id="iconModal" tabindex="-1" aria-labelledby="iconModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="iconModalLabel">アイコンの編集</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>プロフィールに使用する画像をアップロードし、トリミングを行った上で登録してください。</p>
                <div id="icon_croppie"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="modal-dismiss">キャンセル</button>
                <button type="button" class="btn btn-primary" id="icon_submit" data-url="{% url 'common:api_icon_upload' %}">登録</button>
            </div>
        </div>
        </div>
    </div>


    {% if user_form.non_field_errors %}
        <div class="alert alert-danger">
            {% for error in user_form.non_field_errors %}
                {{ error }}<br>
            {% endfor %}
        </div>
    {% endif %}
    {% if profile_form.non_field_errors %}
        <div class="alert alert-danger">
            {% for error in profile_form.non_field_errors %}
                {{ error }}<br>
            {% endfor %}
        </div>
    {% endif %}


    <label class="form-label" for="upload_icon">
        <img src="{{ user.profile.icon.url }}" class="img-profile-lg" alt="アイコン" id="user-icon">
        <input type="file" name="upload_icon" id="upload_icon" class="form-control d-none" aria-describedby="inputFileAddon" accept="image/*" />
    </label>


    {% for field in user_form %}
        <div class="mb-3">
            {{ field |add_label_class:'form-label' }}
            {% if user_form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field field class="form-control" %}
            {% endif %}

            {% if field.help_text %}
                <small class="form-text text-muted">
                    {{ field.help_text }}
                </small>
            {% endif %}
        </div>
    {% endfor %}

    {% for field in profile_form %}
        <div class="mb-3">
            {{ field |add_label_class:'form-label' }}
            {% if profile_form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field field class="form-control" %}
            {% endif %}

            {% if field.help_text %}
                <small class="form-text text-muted">
                    {{ field.help_text }}
                </small>
            {% endif %}
        </div>
    {% endfor %}

    {% csrf_token %}
    <button type="submit" class="btn btn-primary" >保存</button>
</form>
{% endblock %}


{% block extrajs %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'croppie/croppie.min.js' %}"></script>
    <script src="{% static 'common/js/user_icon.js' %}"></script>
{% endblock %}

templates/common/user_settings_list.html
{% extends "base.html" %}

{% block content %}
<div class="list-group">
    <a href="{% url 'common:user_settings_update' %}" class="list-group-item list-group-item-action">
        <span class="me-3"><i class="bi bi-person-fill"></i></span>プロフィールを変更する
    </a>
    <a href="{% url 'common:email_change' %}" class="list-group-item list-group-item-action">
        <span class="me-3"><i class="bi bi-envelope-fill"></i></span>メールアドレスを変更する
    </a>
    <a href="{% url 'common:password_change' %}" class="list-group-item list-group-item-action">
        <span class="me-3"><i class="bi bi-key-fill"></i></span>パスワードを変更する
    </a>
</div>
{% endblock %}